# Generated by Django 5.2.7 on 2025-11-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_star_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework"),
                            ("tool", "Tool"),
                            ("domain", "Domain/Field"),
                            ("topic", "Topic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["-usage_count", "name"],
            },
        ),
    ]
