# Generated by Django 5.2.7 on 2025-11-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("readme_content", models.TextField(blank=True, null=True)),
                ("readme_embedding", models.BinaryField(blank=True, null=True)),
                ("description_embedding", models.BinaryField(blank=True, null=True)),
                ("analysis_date", models.DateTimeField(blank=True, null=True)),
                ("analysis_version", models.CharField(blank=True, max_length=50)),
                ("priority_score", models.FloatField(db_index=True, default=0.0)),
                ("last_commit_date", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("health_score", models.FloatField(default=0.5)),
                ("fetch_attempted", models.BooleanField(default=False)),
                ("fetch_error", models.TextField(blank=True, null=True)),
                ("analysis_attempted", models.BooleanField(default=False)),
                ("analysis_error", models.TextField(blank=True, null=True)),
                (
                    "star",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="content.star",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="stars", to="content.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Star Analysis",
                "verbose_name_plural": "Star Analyses",
                "indexes": [
                    models.Index(
                        fields=["-priority_score"],
                        name="content_sta_priorit_ac62a3_idx",
                    ),
                    models.Index(
                        fields=["analysis_date"], name="content_sta_analysi_60a5c4_idx"
                    ),
                ],
            },
        ),
    ]
