# Generated by Django 5.2.7 on 2025-11-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_staranalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cluster_id", models.IntegerField(db_index=True)),
                ("centroid_distance", models.FloatField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_assignments",
                        to="content.star",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Assignment",
                "verbose_name_plural": "Cluster Assignments",
                "indexes": [
                    models.Index(
                        fields=["cluster_id", "centroid_distance"],
                        name="content_clu_cluster_c8de39_idx",
                    )
                ],
                "unique_together": {("cluster_id", "star")},
            },
        ),
    ]
