# Generated by Django 5.2.7 on 2025-11-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_clusterassignment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clusterassignment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="clusterassignment",
            name="star",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cluster_assignment",
                to="content.star",
            ),
        ),
    ]
