# Generated by Django 5.2.7 on 2025-11-25 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0007_tempstar_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tempstar",
            name="priority_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name="tempstar",
            index=models.Index(
                fields=["-priority_score"], name="implementat_priorit_50312e_idx"
            ),
        ),
    ]
